### PR TITLE
docs(issue-templates): add github issue templates

### PR DESCRIPTION
**Pull request by gonzalespaulb**
## Changes
1. Added BW S&P Github Templates

## Purpose
Autofilled and issuing reference

### CODE REVIEW

**Comment by krferrell** [comment]
Looks good.

**Review by connielion — COMMENTED** [review]
Looks good!

**Review by Lap343 — APPROVED** [review]
I feel like the code was better before but I'll allow it.

**Review by krferrell — APPROVED** [review]
Looks good.

**Pull request merged**
