### PR TITLE
feat(modal):Add shadows to different parts of the modal

### LINKED ISSUE #89: Modal shadows
**Is your feature request related to a problem? Please describe.**
Some modal components don't have shadows and look flat

**Describe the solution you'd like**
Some modal components having shadows

### PR DESCRIPTION
**Pull request by Lap343**
## Changes
1. Added shadows to different parts of the modal

## Purpose
To make the modal look not as flat as it did before

Closes #89

### CODE REVIEW

**Review by Gjhnsn — APPROVED** [review]
looks good

**Review by krferrell — APPROVED** [review]
looks slick

**Review by connielion — APPROVED** [review]
Looks good.

**Review by gonzalespaulb — APPROVED** [review]
LGTM

**Pull request merged**
