### PR TITLE
Clean up code

### LINKED ISSUE #45: Clean up code
**Is your feature request related to a problem? Please describe.**
We have some unused components and some props that are being passed down that are not being used. 

**Describe the solution you'd like**
Going through the entire app and making sure everything is formatted by Prettier and removing any unused components or props.

### PR DESCRIPTION
**Pull request by krferrell**
## Changes
_List Changes Introduced by this PR_
1. Deleted unused files that contained perspective components 
2. Deleted unnecessary comments
3. Removed unused props being passed down

## Purpose
Code and file structure was slightly cluttered with unnecessary things. 

## Approach
Delete unnecessary things. 

Closes #45

### CODE REVIEW

**Review by gonzalespaulb — APPROVED** [review]
Looks cleaner!

**Review by Lap343 — APPROVED** [review]
Code looks pretty

**Review by Gjhnsn — APPROVED** [review]
Looks good!

**Review by connielion — APPROVED** [review]
Looks good.

**Pull request merged**
